# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    access_denied_url: /login
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /login

            logout:
                path:   /logout
                target: /login
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/todo/make, role: ROLE_ADMIN }
        - { path: ^/todo/edit, role: ROLE_ADMIN }
        - { path: ^/todo/create, role: ROLE_USER }
        - { path: ^/todo/delete, role: ROLE_ADMIN }
        - { path: ^/todo/edit/$, role: ROLE_ADMIN }
        - { path: ^/todo/delete/$, role: ROLE_ADMIN }
        - { path: ^/todo/details/$, role: ROLE_USER }
        
        